name: Deploy Django to cPanel

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env File
        run: |
          echo "PROD_SECRET_KEY=${{ secrets.PROD_SECRET_KEY }}" > .env

      - name: Upload Files to cPanel
        uses: appleboy/ssh-action@master
        with:
          server: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          port: 21098
          source: "."
          target: "/home/macreoqn/pardystaging"

      - name: Execute Deployment Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          port: 21098
          script: |
            cd /home/macreoqn/pardystaging

            source /home/macreoqn/virtualenv/pardystaging/3.10/bin/activate

            pip install -r requirements.txt

            python manage.py migrate --settings=pardy.settings.prod

            python manage.py collectstatic --noinput --settings=pardy.settings.prod

            touch /home/macreoqn/tmp/restart.txt